config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'badges/index'
      get 'badges/show'
    end
  end
  root to: redirect('/maintab')
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_for :admins, controllers:{
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  } 
  
  namespace :admins do
    resources :users, only: [:index, :create, :new, :edit, :show, :update, :destroy]
  end
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#guest_sign_in'
    get  'admins/new_administer', to: 'admins/registrations#new_administer'
    post 'admins/new_administer', to: 'admins/registrations#create_administer'
  end

  #サイドバー内リンク
  get 'maintab', to: 'site#index'
  get 'reports', to: 'site#index'
  get 'user_status', to: "site#index"
  get 'contact', to: 'site#index'
  get 'ranking', to: 'ranking#index'

  #その他SPA内
  get 'active_work', to: 'site#index'
  get 'reports/:id/edit', to: 'site#index'
  
  namespace :api do
    namespace :v1 do
      resources :projects, only: %i[index show create update destroy]
      resources :reports, only: %i[index last_report show create update destroy]
      resources :user_statuses do
        member do
          patch "exp_update", to: "user_statuses#exp_update"
        end
      end
      resources :level_settings, only: %i[index]
    end
  end

  #sidekiqダッシュボード用マウント
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web => '/sidekiq'

  post 'ranking/update'

  get '*not_found', to:'application#routing_error'
  post '*not_found', to:'application#routing_error'
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  has_one :user_status, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :tags, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      #user.name = 'ゲスト'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  devise :database_authenticatable,:registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :jwt_authenticatable, jwt_revocation_strategy: self

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :disallow_non_administrators
  skip_before_action :authenticate_user!
  def index
    @users = User.all
    @admins = Admin.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admins_users_path, notice:"アカウント作成完了/admin" 
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @projects = @user.projects
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admins_users_path, notice:"アカウント更新完了/admin" 
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admins_users_path, notice: "アカウントを削除しました/admin" 
  end

  private
  def disallow_non_administrators
    redirect_to root_path, notice: "このアカウントは管理者専用ページにアクセスできません。" unless admin_signed_in?
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/api/v1/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # POST /resource
  def create
    super 
    resource.build_user_status
    resource.save	
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
end

app/views/admins/users/edit.html.erb
<h2 class="row mt-4 pt-5 justify-content-center">登録情報</h2>
<div class="row mt-2 p-4 justify-content-center">
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
    <%= render "devise/shared/error_messages", resource: resource %>
    <div class="field form-group row">
      <%= f.label :email, class:"col-sm-6 col-form-label" %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control" %>
    </div>
    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
    <% end %>
    <div class="field form-group row">
      <%= f.label :password, class:"col-sm-6 col-form-label" %> <i>(leave blank if you don't want to change it)</i><br />
      <%= f.password_field :password, autocomplete: "new-password", class:"form-control" %>
      <% if @minimum_password_length %>
        <br />
        <em><%= @minimum_password_length %> characters minimum</em>
      <% end %>
    </div>
    <div class="field form-group row">
      <%= f.label :password_confirmation, class:"col-sm-6 col-form-label" %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class:"form-control" %>
    </div>
    <div class="field form-group row">
      <%= f.label :current_password, class:"col-sm-6 col-form-label" %> <i>(we need your current password to confirm your changes)</i><br />
      <%= f.password_field :current_password, autocomplete: "current-password", class:"form-control" %>
    </div>
    <div class="actions">
      <%= f.submit t('.update'), class:"btn btn-primary mt-4" %>
    </div>
  <% end %>
</div>
<hr>
<h3>アカウント削除</h3>
<p>お気に召しませんか? <%= button_to "アカウント削除", registration_path(resource_name), data: { confirm: "削除してもよろしいですか?" }, method: :delete %></p>
<%= link_to "戻る", :back %>

app/views/admins/users/index.html.erb
<h1 class="pt-5">管理者画面:Users</h1>
<table>
  <thead>
    <tr>
      <th>メールアドレス</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to I18n.t('.destroy'),admins_user_path(user), method: :delete, data: { confirm: '削除してもよろしいですか?' } %></td>  
      </tr>
    <% end %>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th>管理者ユーザー</th>
    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
  <%= link_to '管理者作成', admins_new_administer_path, class: "btn btn-secondary", id: "new-admin" %>
</div>