config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'badges/index'
      get 'badges/show'
    end
  end
  root to: redirect('/maintab')
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_for :admins, controllers:{
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  } 
  
  namespace :admins do
    resources :users, only: [:index, :create, :new, :edit, :show, :update, :destroy]
  end
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#guest_sign_in'
    get  'admins/new_administer', to: 'admins/registrations#new_administer'
    post 'admins/new_administer', to: 'admins/registrations#create_administer'
  end

  #サイドバー内リンク
  get 'maintab', to: 'site#index'
  get 'reports', to: 'site#index'
  get 'user_status', to: "site#index"
  get 'contact', to: 'site#index'
  get 'ranking', to: 'ranking#index'

  #その他SPA内
  get 'active_work', to: 'site#index'
  get 'reports/:id/edit', to: 'site#index'
  
  namespace :api do
    namespace :v1 do
      resources :projects, only: %i[index show create update destroy]
      resources :reports, only: %i[index last_report show create update destroy]
      resources :user_statuses do
        member do
          patch "exp_update", to: "user_statuses#exp_update"
        end
      end
      resources :level_settings, only: %i[index]
    end
  end

  #sidekiqダッシュボード用マウント
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web => '/sidekiq'

  post 'ranking/update'

  get '*not_found', to:'application#routing_error'
  post '*not_found', to:'application#routing_error'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def self.guest
    find_or_create_by!(email: 'guestadmin@example.com') do |admin|
      admin.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_one :badge_settings, dependent: :destroy
  has_many :badge_user_statuses
  has_many :user_statuses, through: :badge_user_statuses
end

app/models/badge_setting.rb
class BadgeSetting < ApplicationRecord
  belongs_to :badge
end

app/models/badge_user_status.rb
class BadgeUserStatuses < ApplicationRecord
  belongs_to :user_status
  belongs_to :badge
end

app/models/level_setting.rb
class LevelSetting < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  validates :title, 
    presence: true,
    length: { maximum: 100 }
  validates :deadline, presence: true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  validates :y_record, 
    presence: true,
    length: { maximum: 2000 }
  validates :w_record, 
    presence: true,
    length: { maximum: 2000 }
  validates :t_record, 
    presence: true,
    length: { maximum: 2000 }
end

app/models/report_tag.rb
class ReportTag < ApplicationRecord
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  has_one :user_status, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :tags, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      #user.name = 'ゲスト'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  devise :database_authenticatable,:registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :jwt_authenticatable, jwt_revocation_strategy: self

end

app/models/user_status.rb
class UserStatus < ApplicationRecord
  belongs_to :user
  has_many :badge_user_statuses, dependent: :destroy
  has_many :badges, through: :badge_userstatuses

  def exp_update(exp)
    before_exp = self.exp
    self.exp += (exp)
    self.next_level_exp -= (exp)
    self.last_achievemented_at = Date.today
    level_settings = LevelSetting.all.order(level: :desc)
    update_level = level_settings.find { |level|
      level.exp > before_exp && level.exp <= self.exp
    }
    transaction do
      if self.next_level_exp <= 0
        self.level = update_level.level
        self.next_level_exp = update_level.next_exp - self.exp
        bonus = self.level * 100
        self.score += bonus
        self.save!
        return { user_status: self, flash_message: "レベルアップ！ スコアボーナス+#{bonus}" }
      end
      self.save!
      return self 
    end
  end
end

app/controllers/admins/unlocks_controller.rb
class Admins::UnlocksController < Devise::UnlocksController
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :disallow_non_administrators
  skip_before_action :authenticate_user!
  def index
    @users = User.all
    @admins = Admin.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admins_users_path, notice:"アカウント作成完了/admin" 
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @projects = @user.projects
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admins_users_path, notice:"アカウント更新完了/admin" 
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admins_users_path, notice: "アカウントを削除しました/admin" 
  end

  private
  def disallow_non_administrators
    redirect_to root_path, notice: "このアカウントは管理者専用ページにアクセスできません。" unless admin_signed_in?
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, unless: :admin_signed_in?
  
  def after_sign_in_path_for(resource)
    root_path
  end

  rescue_from Exception,                      with: :_render_500
  rescue_from ActiveRecord::RecordNotFound,   with: :_render_404
  rescue_from ActionController::RoutingError, with: :_render_404
  
  def routing_error
    raise ActionController::RoutingError, params[:path]
  end

  def _render_404(e = nil)
    logger.info "Rendering 404 with excaption: #{e.message}" if e
    if request.format.to_sym == :json
      render json: { error: "404 Not Found" }, status: :not_found
    else
      render "errors/404.html", status: :not_found, formats: :html
    end
  end

  def _render_500(e = nil)
    logger.error "Rendering 500 with excaption: #{e.message}" if e
    if request.format.to_sym == :json
      render json: { error: "500 Internal Server Error" }, status: :internal_server_error
    else
      render "errors/500.html", status: :internal_server_error, formats: :html
    end
  end

end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  def index
    @ranking_list = UserStatus.all.where.not(id: 20).order(score: :desc)
  end

  def update
    ScoreUpdateJob.perfoem_later
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_statuses_helper.rb
module UserStatusesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chakka</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'index' %>
    <script src="https://kit.fontawesome.com/b893fb5e5f.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  </head>
  <body>
    <header>
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-info shadow fixed-top">
          <a class="navbar-brand mb-0 h1" href="/">CHAKKA!</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto ">
              <% if user_signed_in? %>
                <li class="nav-item active">
                  <%= link_to '/users/edit', class: "nav-link", id: "edit-link" do %><i class="fa-solid fa-user"> <%= current_user.email %> でログイン中</i><% end %>
                </li>
                <li class="nav-item active" >
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link", id: "logout" do %><i class="fa-solid fa-right-from-bracket"> ログアウト</i><% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to root_path, class: "nav-link" do %><i class="fa-solid fa-house">ホーム</i><% end %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item active">
                  <%= link_to '/admins/edit', class: "nav-link" do %><i class="fa-solid fa-user"> <%= current_admin.email %>(管理者)でログイン中</i><% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to admins_users_path, class: "nav-link", id: "users-index" do %><i class="fa-solid fa-house">管理画面へ</i><% end %>
                </li>
                <li class="nav-item active" >
                  <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link" do %><i class="fa-solid fa-right-from-bracket"> ログアウト</i><% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to root_path, class: "nav-link" do %><i class="fa-solid fa-house">ホーム</i><% end %>
                </li>
              <% else %>
                <li class="nav-item active">
                  <%= link_to new_user_registration_path, class: "nav-link" do %><i class="fa-solid fa-user-plus"> アカウントを新規作成 </i><% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to new_user_session_path, class: "nav-link" do %><i class="fa-solid fa-right-to-bracket"> ログイン </i><% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <div class="container">
      <div class="row mr-2 pt-4 justify-content-end fixed-bottom text-right">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>